### ISSUE TITLE
harmonize_data vs. convert_to_log

### ISSUE THREAD

**Issue by martinobertoni** [mims-harvard/TDC#153]
Hi and thanks for this great tool!
Just wanted to mention 2 points:
1- the function harmonize_data does not modify the data but simply return an aggregated dataframe (this does not match how the function is presented to work (e.g. in here https://tdcommons.ai/multi_pred_tasks/dti/ at bindingDB paragraph)
2- harmonize_data takes the min of the aggregation, but if data had been previously converted to log this is behaving in the opposite (given the -log in the conversion we now want higher values)
Hope this helps improving your tool, best

**Comment by alex-golts** [comment]
I also encountered this bug. 
If I may add an additional comment, also concerning the harmonize_affinities function: 
currently it returns an error if the database name is not one of 'bindingdb_ki', 'bindingdb_kd', or 'bindingdb_ic50' (apparently since in other existing names the duplicated are already removed).
I'd consider removing this check, because for example in my use case I use a custom name (which doesn't already exist in TDCs metadata), so in this case the function would crash even though I do have duplicates.

applying the function where there are no duplicates, should not cause any harm anyway, right?

**Comment by kexinhuang12345** [comment]
Hi! Sorry for the late update, was busy with some work! Happy to share these concerns have all been incorporated in this PR: https://github.com/mims-harvard/TDC/commit/fc3e55ead15c2fc0602b0f303eb427620c342c86

(1) now it automatically updates the original dataframe so that you can do data split, along with other functions.
(2) after taking the log, the max_affinity would take the maximum
(3) the restriction on "bindingdb" dataset only has been lifted

Let us know if you have any other question! This would be updated to pip soon, now you should be able to run it using the git source version!
