### ISSUE TITLE
Small discrepancies in the documentation of oracles

### ISSUE THREAD

**Issue by miguelgondu** [mims-harvard/TDC#244]
**Describe the bug**

I am currently creating an interface for TDC s.t. it works well with SELFIES and other representations of small molecules. In the process I've noticed the following in [the documentation of oracles](https://tdcommons.ai/functions/oracles):

1. It invites the user to create a python env using version 3.7, which is no longer supported by Conda.
2. In the case of `Sitagliptin_MPO`,`Zaleplon_MPO`, `Isomers_C7H8N2O2`, and `Isomers_C9H10N2O2PF2Cl`, I'm getting different values for the oracle:

**To Reproduce**

Using `PyTDC==0.4.7`, run

```
from tdc import Oracle

oracle = Oracle(name="Sitagliptin_MPO")

# Running the oracle in the example provided by the docs:
oracle("CC(C)(C)[C@H]1CCc2c(sc(NC(=O)COc3ccc(Cl)cc3)c2C(N)=O)C1")
```

**Expected behavior**

- For `Sitagliptin_MPO` I get `3.34970667598234e-12` instead of `0.00562486906491877`
- For `Zaleplon_MPO` I get `0.0019017991803329235` instead of `7.752152611462035e-05`
- For `Isomers_C7H8N2O2` I get `2.1987591132394053e-34` instead of `7.077155389805107e-22`
- For `Isomers_C9H10N2O2PF2Cl` I get `1.713908431542013e-15` instead of `3.775134544279098e-11`

**Environment:**
- OS: MacOS Sonoma 14.4.1
- Python version: 3.10.12
- TDC version: 0.4.7
- Any other relevant information: Can be replicated in Colab easily.

**Comment by amva13** [comment]
I'd imagine the notebook is using an older scikit version in the <= 0.24 range

**Comment by amva13** [comment]
https://tdcommons.ai/functions/oracles/
https://github.com/mims-harvard/TDC/blob/main/tutorials/TDC_105_Oracle.ipynb
https://dataverse.harvard.edu/file.xhtml?fileId=6413420&version=82.0
https://github.com/mims-harvard/TDC/blob/1d8df1592fbd2ea7cdb8ff2b8fd183dc602625a6/tdc/utils/load.py#L159

**Comment by amva13** [comment]
making note here. this and many similar issues probably due to

<blockquote class="protonmail_quote sh-color-black sh-color" type="cite" style="margin: 0px; padding: 0px 0px 0px 1.25rem; border-left: 0px; background-image: -webkit-linear-gradient(left, rgb(237, 237, 237) 75%, rgb(237, 237, 237) 75%); background-size: 1px 1px; background-position: left center; background-repeat: repeat-y; color: rgba(0, 0, 0, 0.6); font-family: &quot;Superhuman Adelle Email&quot;, color-emoji-override, sans-serif, &quot;Apple Color Emoji&quot;, emoji-flag-fallbacks, &quot;Segoe UI Emoji&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
1 repository in your mims-harvard organization might be affected by a security vulnerability in nltk  ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts  mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt | 1 repository in your mims-harvard organization might be affected by a security vulnerability in nltk | 1 repository in your mims-harvard organization might be affected by a security vulnerability in nltk |   | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts  mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts  mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts  mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts |   |   |   |   | View all alerts | View all alerts | View all alerts |   | mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt |   | mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 repository in your mims-harvard organization might be affected by a security vulnerability in nltk | 1 repository in your mims-harvard organization might be affected by a security vulnerability in nltk |  
1 repository in your mims-harvard organization might be affected by a security vulnerability in nltk
 
ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts  mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts  mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts  mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts |   |   |   |   | View all alerts | View all alerts | View all alerts |   | mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt |   | mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt
ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts  mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts  mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts |   |   |   |   | View all alerts | View all alerts | View all alerts |   | mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt |   | mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt
ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts  mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts |   |   |   |   | View all alerts | View all alerts | View all alerts |   | mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt |   | mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt
ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts | ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts |   |   |   |   | View all alerts | View all alerts | View all alerts |  
ntlk unsafe deserialization vulnerability High severity  nltkCVE-2024-39705 View all alerts |   |   |   |   | View all alerts | View all alerts | View all alerts |  
 
 
 
 
View all alerts | View all alerts | View all alerts
View all alerts | View all alerts
View all alerts
 
mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt |   | mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt
  | mims-harvard/TDCexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txtexamples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt

</blockquote>1 repository in your mims-harvard organization might be affected by a security vulnerability in nltk
 


 
ntlk unsafe deserialization vulnerability
 High severity
 
 nltk

CVE-2024-39705

 
 
 mims-harvard/TDC

[examples/generation/docking_generation/guacamol_tdc/guacamol_baselines/dockers/requirements.txt](https://github.com/mims-harvard/TDC/security/dependabot/799)
[examples/generation/docking_generation/guacamol_tdc/guacamol_baselines/requirements.txt](https://github.com/mims-harvard/TDC/security/dependabot/800)

**Comment by amva13** [comment]
https://github.com/mims-harvard/TDC/issues/291 <-- solution being worked on in this ticket. follow this one.

**Comment by amva13** [comment]
please see https://github.com/mims-harvard/TDC/issues/235#issuecomment-2207244304 ; this is now closed
